export default {
  FILEFIELD_ADD_FILE: 'FILEFIELD_ADD_FILE',
  FILEFIELD_SET_FILES: 'FILEFIELD_SET_FILES',
  FILEFIELD_FAIL_UPLOAD: 'FILEFIELD_FAIL_UPLOAD',
  FILEFIELD_REMOVE_FILE: 'FILEFIELD_REMOVE_FILE',
  FILEFIELD_SUCCEED_UPLOAD: 'FILEFIELD_SUCCEED_UPLOAD',
  FILEFIELD_UPDATE_QUEUED_FILE: 'FILEFIELD_UPDATE_QUEUED_FILE',
};
