export default {
  DEFINE_IMAGE_SIZE_PRESETS: 'DEFINE_IMAGE_SIZE_PRESETS',
  INIT_FORM_SCHEMA_STACK: 'INIT_FORM_SCHEMA_STACK',
  POP_FORM_SCHEMA: 'POP_FORM_SCHEMA',
  PUSH_FORM_SCHEMA: 'PUSH_FORM_SCHEMA',
  RESET: 'RESET',
  RESET_FORM_STACK: 'RESET_FORM_STACK'
};
