export default {
  CONFIRM_DELETION_ASK: 'CONFIRM_DELETION_ASK',
  CONFIRM_DELETION_CONFIRM: 'CONFIRM_DELETION_CONFIRM',
  CONFIRM_DELETION_CANCEL: 'CONFIRM_DELETION_CANCEL',
  CONFIRM_DELETION_RESET: 'CONFIRM_DELETION_RESET',
  CONFIRM_DELETION_MODAL_CLOSE: 'CONFIRM_DELETION_MODAL_CLOSE'
};
