// This file was generated by silverstripe/cow from client/lang/src/ar.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ar', {
    "AssetAdmin.ConfirmDelete": "هل تريد حقًا حذف هذا المجلد وكل ما يحتويه من ملفات؟",
    "Folder.Name": "اسم المجلد"
});
}