// This file was generated by silverstripe/cow from client/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "AssetAdmin.ConfirmDelete": "Do you really want to delete this folder and all contained files?",
    "AssetGalleryField.ADD_FOLDER_BUTTON": "Add folder",
    "AssetGalleryField.BACK": "Back",
    "AssetGalleryField.BULK_ACTIONS_CONFIRM": "Are you sure you want to %s these files?",
    "AssetGalleryField.BULK_ACTIONS_DELETE": "Delete",
    "AssetGalleryField.BULK_ACTIONS_PLACEHOLDER": "Select an action...",
    "AssetGalleryField.CANCEL": "Cancel",
    "AssetGalleryField.CONFIRMDELETE": "Are you sure you want to delete this record?",
    "AssetGalleryField.CREATED": "First uploaded",
    "AssetGalleryField.DELETE": "Delete",
    "AssetGalleryField.DIM": "Dimensions",
    "AssetGalleryField.DROPZONE_CANCEL_UPLOAD": "Cancel upload",
    "AssetGalleryField.DROPZONE_CANCEL_UPLOAD_CONFIRMATION": "Are you sure you want to cancel this upload?",
    "AssetGalleryField.DROPZONE_DEFAULT_MESSAGE": "Drop files here to upload",
    "AssetGalleryField.DROPZONE_FAILED_UPLOAD": "Failed to upload file",
    "AssetGalleryField.DROPZONE_FALLBACK_MESSAGE": "Your browser does not support drag'n'drop file uploads.",
    "AssetGalleryField.DROPZONE_FALLBACK_TEXT": "Please use the fallback form below to upload your files like in the olden days.",
    "AssetGalleryField.DROPZONE_FILE_TOO_BIG": "File is too big. Max filesize: %sMiB.",
    "AssetGalleryField.DROPZONE_INVALID_FILE_TYPE": "You can't upload files of this type.",
    "AssetGalleryField.DROPZONE_MAX_FILES_EXCEEDED": "You can not upload any more files.",
    "AssetGalleryField.DROPZONE_REMOVE_FILE": "Remove file",
    "AssetGalleryField.DROPZONE_RESPONSE_ERROR": "Server responded with an error.",
    "AssetGalleryField.DROPZONE_SUCCESS_UPLOAD": "File uploaded",
    "AssetGalleryField.DROPZONE_UPLOAD": "Upload",
    "AssetGalleryField.EDIT": "Edit",
    "AssetGalleryField.FILENAME": "Filename",
    "AssetGalleryField.FILTER_DATE_ASC": "oldest",
    "AssetGalleryField.FILTER_DATE_DESC": "newest",
    "AssetGalleryField.FILTER_TITLE_ASC": "title a-z",
    "AssetGalleryField.FILTER_TITLE_DESC": "title z-a",
    "AssetGalleryField.LASTEDIT": "Last changed",
    "AssetGalleryField.LOADMORE": "Load more",
    "AssetGalleryField.NOITEMSFOUND": "No items found",
    "AssetGalleryField.SAVE": "Save",
    "AssetGalleryField.PUBLISH": "Publish",
    "AssetGalleryField.SELECT": "Select",
    "AssetGalleryField.SIZE": "Size",
    "AssetGalleryField.TITLE": "Title",
    "AssetGalleryField.TYPE": "File type",
    "AssetGalleryField.URL": "URL",
    "AssetGalleryField.CLOSE": "Close",
    "Folder.Name": "Folder name"
});
}
