// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "AssetAdmin.ADD_FOLDER_BUTTON": "Aldoni dosierujon",
    "AssetAdmin.BACK": "Reen",
    "AssetAdmin.BACK_DESCRIPTION": "Navigi supren unu nivelon",
    "AssetAdmin.BULK_ACTIONS_ARCHIVE": "Arkivo"
});
}