// This file was generated by silverstripe/cow from client/lang/src/eo.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "AssetAdmin.ConfirmDelete": "Ĉu vi vere volas forigi ĉi tiun dosierujon kaj ĉiujn dosierojn en ĝi?",
    "Folder.Name": "Nomo de dosierujo"
});
}