// This file was generated by silverstripe/cow from client/lang/src/fa_IR.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fa_IR', {
    "AssetAdmin.ConfirmDelete": "Do you really want to delete this folder and all contained files?",
    "Folder.Name": "نام پوشه"
});
}