// This file was generated by silverstripe/cow from client/lang/src/fi.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi', {
    "AssetAdmin.ConfirmDelete": "Haluatko varmasti poistaa tämän kansion ja kaikki tiedostot sen sisällä?",
    "Folder.Name": "Kansion nimi"
});
}