// This file was generated by silverstripe/cow from client/lang/src/it.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "AssetAdmin.ConfirmDelete": "Vuoi veramente eliminare questa cartella e tutti i suoi file?",
    "Folder.Name": "Nome cartella"
});
}