// This file was generated by silverstripe/cow from client/lang/src/ko.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ko', {
    "AssetAdmin.ConfirmDelete": "이 폴더와 폴더에 포함된 모든 파일을 정말 삭제합니까?",
    "Folder.Name": "폴더 이름"
});
}