// This file was generated by silverstripe/cow from client/lang/src/lt.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('lt', {
    "AssetAdmin.ConfirmDelete": "Ar tikrai norite ištrinti šį katalogą ir visas jame esančias bylas?",
    "Folder.Name": "Katalogo pavadinimas"
});
}