// This file was generated by silverstripe/cow from client/lang/src/mi.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('mi', {
    "AssetAdmin.ConfirmDelete": "Kei te tino hiahia muku i tēnei kōpaki me ngā kōnae i roto?",
    "Folder.Name": "Ingoa kōpaki"
});
}