// This file was generated by silverstripe/cow from client/lang/src/pl.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "AssetAdmin.ConfirmDelete": "Czy na pewno usunąć ten folder i wszystkie pliki w nim zawarte?",
    "Folder.Name": "Nazwa folderu"
});
}