// This file was generated by silverstripe/cow from client/lang/src/ro.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ro', {
    "AssetAdmin.ConfirmDelete": "Doriţi ştergerea acestui dosar precum şi a tuturor fişierelor conţinute?",
    "Folder.Name": "Nume dosar"
});
}