// This file was generated by silverstripe/cow from client/lang/src/ru.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "AssetAdmin.ConfirmDelete": "Вы действительно хотите удалить эту директорию и все файлы в ней?",
    "Folder.Name": "Имя директории"
});
}