// This file was generated by silverstripe/cow from client/lang/src/sk.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "AssetAdmin.ConfirmDelete": "Skutočne chcete smazať túto zložku a všetky obsahujúce súbory?",
    "Folder.Name": "Názov složky"
});
}