// This file was generated by silverstripe/cow from client/lang/src/sr_RS@latin.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr_RS@latin', {
    "AssetAdmin.ConfirmDelete": "Da li zaista želite da izbrišete ovu fasciklu i sve datoteke sadržane u njoj?",
    "Folder.Name": "Ime fascikle"
});
}