// This file was generated by silverstripe/cow from client/lang/src/zh.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('zh', {
    "AssetAdmin.ConfirmDelete": "是否确定删除该文件夹以及所有包含的文件？",
    "Folder.Name": "文件夹名称"
}
);
}