// This file was generated by silverstripe/cow from admin/javascript/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('en', {
	"AssetGalleryField.FILTER_TITLE_ASC": "title a-z",
	"AssetGalleryField.FILTER_TITLE_DESC": "title z-a",
	"AssetGalleryField.FILTER_DATE_DESC": "newest",
	"AssetGalleryField.FILTER_DATE_ASC": "oldest",
	"AssetGalleryField.LOADMORE": "Load more",
	"AssetGalleryField.BACK": "Back",
	"AssetGalleryField.CONFIRMDELETE": "Are you sure you want to delete this record?",
	"AssetGalleryField.TYPE": "File type",
	"AssetGalleryField.SIZE": "Size",
	"AssetGalleryField.URL": "URL",
	"AssetGalleryField.CREATED": "First uploaded",
	"AssetGalleryField.LASTEDIT": "Last changed",
	"AssetGalleryField.DIM": "Dimensions",
	"AssetGalleryField.SAVE": "Save",
	"AssetGalleryField.CANCEL": "Cancel",
	"AssetGalleryField.TITLE": "Title",
	"AssetGalleryField.FILENAME": "Filename"
});
}