export const GALLERY = {
    ADD_FILE: 'ADD_FILE',
    UPDATE_FILE: 'UPDATE_FILE',
    SELECT_FILE: 'SELECT_FILE',
    DESELECT_FILES: 'DESELECT_FILES',
    SET_EDITING: 'SET_EDITING',
    SET_FOCUS: 'SET_FOCUS'
}
