export default {
  UPLOADFIELD_SET_FORM_SCHEMA_FILES_HASH: 'UPLOADFIELD_SET_FORM_SCHEMA_FILES_HASH',
  UPLOADFIELD_ADD_FILE: 'UPLOADFIELD_ADD_FILE',
  UPLOADFIELD_SET_FILES: 'UPLOADFIELD_SET_FILES',
  UPLOADFIELD_REMOVE_FILE: 'UPLOADFIELD_REMOVE_FILE',
  UPLOADFIELD_UPLOAD_FAILURE: 'UPLOADFIELD_UPLOAD_FAILURE',
  UPLOADFIELD_UPLOAD_SUCCESS: 'UPLOADFIELD_UPLOAD_SUCCESS',
  UPLOADFIELD_UPDATE_QUEUED_FILE: 'UPLOADFIELD_UPDATE_QUEUED_FILE',
};
