export default {
  FILEFIELD_ADD_FILE: 'FILEFIELD_ADD_FILE',
  FILEFIELD_SET_FILES: 'FILEFIELD_SET_FILES',
  FILEFIELD_REMOVE_FILE: 'FILEFIELD_REMOVE_FILE',
  FILEFIELD_UPLOAD_FAILURE: 'FILEFIELD_UPLOAD_FAILURE',
  FILEFIELD_UPLOAD_SUCCESS: 'FILEFIELD_UPLOAD_SUCCESS',
  FILEFIELD_UPDATE_QUEUED_FILE: 'FILEFIELD_UPDATE_QUEUED_FILE',
};
